const fs = require("node:fs/promises");
const path = require("node:path");
const crypto = require("node:crypto");
const { spawnSync } = require("node:child_process");

const ROOT = path.resolve(__dirname, "..");
const BASE = path.join(ROOT, "static", "2026_summer_kids");
const DATA_FILE = path.join(BASE, "data", "activities.json");
const DOCS_DIR = path.join(BASE, "docs");
const REPORT_FILE = path.join(DOCS_DIR, "update-report.md");

const DATE_PATTERN =
  /(?:20\d{2}[./-]\d{1,2}[./-]\d{1,2}|20\d{2}\s*年\s*\d{1,2}\s*月\s*\d{1,2}\s*日|\d{1,2}\s*月\s*\d{1,2}\s*日|\d{1,2}\/\d{1,2})/g;

function todayInTaipei() {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Taipei",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date());
}

function normalizeText(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\s+/g, " ")
    .trim();
}

function pageTitle(html) {
  const match = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  return match ? normalizeText(match[1]).slice(0, 120) : "";
}

function dateSnippets(text) {
  return Array.from(new Set(text.match(DATE_PATTERN) || [])).slice(0, 12);
}

function hash(value) {
  return crypto.createHash("sha256").update(value).digest("hex").slice(0, 16);
}

async function checkSource(source) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 20000);

  try {
    const response = await fetch(source.url, {
      signal: controller.signal,
      headers: {
        "user-agent": "summer-kids-source-checker/1.0 (+https://audachang.github.io/)",
      },
    });
    const html = await response.text();
    const text = normalizeText(html);

    return {
      label: source.label,
      url: source.url,
      ok: response.ok,
      status: response.status,
      title: pageTitle(html),
      contentHash: hash(text),
      dateSnippets: dateSnippets(text),
      checkedAt: todayInTaipei(),
      error: null,
    };
  } catch (error) {
    return {
      label: source.label,
      url: source.url,
      ok: false,
      status: null,
      title: "",
      contentHash: null,
      dateSnippets: [],
      checkedAt: todayInTaipei(),
      error: error.name === "AbortError" ? "timeout" : error.message,
    };
  } finally {
    clearTimeout(timeout);
  }
}

function mergeDiagnostics(activity, diagnostics) {
  const next = { ...activity };
  next.lastChecked = todayInTaipei();
  next.sourceDiagnostics = diagnostics.map((item) => ({
    label: item.label,
    url: item.url,
    ok: item.ok,
    status: item.status,
    title: item.title,
    contentHash: item.contentHash,
    dateSnippets: item.dateSnippets,
    checkedAt: item.checkedAt,
    error: item.error,
  }));
  return next;
}

function renderReport(payload, checks) {
  const lines = [
    "# Summer Kids Source Update Report",
    "",
    `Checked at: ${todayInTaipei()}`,
    "",
    "This report is generated by `scripts/update_summer_kids_sources.js`.",
    "The script updates source diagnostics and Markdown docs. It does not rewrite activity descriptions from raw website text automatically.",
    "",
    "## Summary",
    "",
  ];

  const allChecks = checks.flatMap((item) => item.diagnostics);
  const failed = allChecks.filter((item) => !item.ok);
  lines.push(`- Activities checked: ${payload.activities.length}`);
  lines.push(`- Source URLs checked: ${allChecks.length}`);
  lines.push(`- Failed source checks: ${failed.length}`);
  lines.push("");

  lines.push("## Details");
  lines.push("");

  for (const item of checks) {
    lines.push(`### ${item.activity.city}｜${item.activity.title}`);
    lines.push("");
    for (const source of item.diagnostics) {
      lines.push(`- ${source.label}`);
      lines.push(`  - URL: ${source.url}`);
      lines.push(`  - Status: ${source.ok ? "OK" : "Needs review"}${source.status ? ` (${source.status})` : ""}`);
      if (source.error) lines.push(`  - Error: ${source.error}`);
      if (source.title) lines.push(`  - Page title: ${source.title}`);
      if (source.dateSnippets.length) lines.push(`  - Date-like snippets: ${source.dateSnippets.join(", ")}`);
      lines.push(`  - Content hash: ${source.contentHash || "n/a"}`);
    }
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}

function runDocGenerator() {
  const result = spawnSync(process.execPath, [path.join(__dirname, "generate_summer_kids_docs.js")], {
    cwd: ROOT,
    stdio: "inherit",
  });

  if (result.status !== 0) {
    throw new Error("Markdown generation failed");
  }
}

async function main() {
  const payload = JSON.parse(await fs.readFile(DATA_FILE, "utf8"));
  payload.meta.updatedAt = todayInTaipei();

  const checks = [];
  const nextActivities = [];

  for (const activity of payload.activities) {
    const diagnostics = [];
    for (const source of activity.sources || []) {
      diagnostics.push(await checkSource(source));
    }
    checks.push({ activity, diagnostics });
    nextActivities.push(mergeDiagnostics(activity, diagnostics));
  }

  payload.activities = nextActivities;

  await fs.mkdir(DOCS_DIR, { recursive: true });
  await fs.writeFile(DATA_FILE, `${JSON.stringify(payload, null, 2)}\n`, "utf8");
  await fs.writeFile(REPORT_FILE, renderReport(payload, checks), "utf8");
  runDocGenerator();
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
